### ISSUE TITLE
Bug: unable to create an opslevel_check_repository_search resource 

### ISSUE THREAD

**Issue by bassco** [OpsLevel/terraform-provider-opslevel#428]
Issue occurs with v1.1.1 and v1.1.3

```hcl
  # opslevel_check_repository_search.streaming_go_sdk_check will be created
  + resource "opslevel_check_repository_search" "streaming_go_sdk_check" {
      + category                = "REDACTED"
      + description             = (known after apply)
      + enabled                 = false
      + file_contents_predicate = {
          + type  = "does_not_match_regex"
          + value = "git\\.redacted\\.com\\/streaming-platform\\/streaming-sdk-go(?:\\/v2)?\\s+v(2\\.0\\.[0-9]|1\\.\\d+\\.\\d+|0\\.\\d+\\.\\d+)"
        }
      + file_extensions         = [
          + "mod",
        ]
      + filter                  = "REDACTED"
      + id                      = (known after apply)
      + level                   = "REDACTED"
      + name                    = "Streaming Go SDK version check"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

❯ terragrunt apply /tmp/plan.out
opslevel_check_repository_search.streaming_go_sdk_check: Creating...

Error: opslevel client error

  with opslevel_check_repository_search.streaming_go_sdk_check,
  on repository_search_check.tf line 1, in resource "opslevel_check_repository_search" "streaming_go_sdk_check":
   1: resource "opslevel_check_repository_search" "streaming_go_sdk_check" {

Unable to create check_repository_search, got error: OpsLevel API Errors:
	- 'fileContentsPredicate' Invalid predicate type for fileContentsPredicate
```

We are unable to use 1.2.3 due to #417

**Comment by bassco** [comment]
I thought I would create the rubric check in the UI and then import the resource. Looks like the graphql does not support the regex matches. Only predicates allowed are"

* contains
* does_not_contain

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/d1911e33-8af0-4d9a-af7b-e5650fb8457e">

**Comment by rocktavious** [comment]
@bassco you used `does_not_match_regex` it looks like based on the above terraform but the check only supports `does_not_contain` and `contains`

If you need support for `does_not_match_regex` you'll need to reachout to your Customer Success representative and ask to file a feature request.  From the little i know about this check type i think we don't support `does_not_match_regex` because the API's we use for Github and Gitlab and such don't support it.  So you might be better off using the `Repo Grep` check which uses `git clone` and `ripgrep` under the hood.

As it stands today we mirror / match what the API does/supports.

**Comment by bassco** [comment]
Thanks. We figured as much. Thanks for the background info on how it works under the hood. We did revert back to the repo grep functionality.
